name: torchvideo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - av=6.2.0
  - ffmpeg
  - lintel=1.0
  - numpy=1.17.0
  - pandas==0.25.0
  - pytorch=1.2.0
  - python=3.7.3
  - pip
  - torchvision=0.4.0
  - pre_commit==1.18.0
  - pip:
    - hypothesis==4.32.3
    - pytest==5.0.1
    - pytest-cov==2.7.1
    - pytest-xdist==1.29.0
    - pyfakefs==3.6
    - moviepy==1.0.0
    - gulpio==531.53
    - sphinx==2.1.2
    - sphinx_autodoc_typehints==1.7.0
    - sphinx_rtd_theme==0.4.3
    - pillow-simd==6.0.0.post0
    - scipy==1.3.1
    - mypy==0.720
