name: torchvideo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - av=6.1.0=py36h7273d18_0
  - bzip2=1.0.6=h470a237_2
  - ca-certificates=2018.11.29=ha4d7672_0
  - certifi=2018.11.29=py36_1000
  - click=7.0=py_0
  - cycler=0.10.0=py_1
  - expat=2.2.5=hfc679d8_2
  - ffmpeg=4.0.2=ha0c5888_2
  - fontconfig=2.13.1=h65d0f4c_0
  - gettext=0.19.8.1=h5e8e0c9_1
  - glib=2.56.2=h464dc38_1
  - gmp=6.1.2=hfc679d8_0
  - gnutls=3.5.19=h2a4e5f8_1
  - icu=58.2=hfc679d8_0
  - kiwisolver=1.0.1=py36h2d50403_2
  - libiconv=1.15=h470a237_3
  - libuuid=2.32.1=h470a237_2
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_5
  - lintel=1.0=py36he85015d_0
  - matplotlib=3.0.2=py36h8a2030e_1
  - matplotlib-base=3.0.2=py36h20b835b_1
  - nettle=3.3=0
  - openh264=1.8.0=hd28b015_0
  - openssl=1.0.2p=h470a237_1
  - pthread-stubs=0.4=h470a237_1
  - pyparsing=2.3.0=py_0
  - pyqt=5.6.0=py36h8210e8a_8
  - python=3.6.6=h5001a0f_3
  - python-dateutil=2.7.5=py_0
  - sip=4.18.1=py36hfc679d8_0
  - tornado=5.1.1=py36h470a237_0
  - x264=1!152.20180717=h470a237_1
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - blas=1.0=mkl
  - cffi=1.11.5=py36he75722e_1
  - dbus=1.13.2=h714fa37_1
  - freetype=2.9.1=h8a8886c_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - intel-openmp=2019.1=144
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.35=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - mkl=2019.1=144
  - mkl_fft=1.0.6=py36hd81dba3_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.15.4=py36h7e9f1db_0
  - numpy-base=1.15.4=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - pcre=8.42=h439df22_0
  - pillow=5.3.0=py36h34e0f95_0
  - pip=18.1=py36_0
  - pycparser=2.19=py36_0
  - qt=5.6.3=h8bf5577_3
  - readline=7.0=h7b6447c_5
  - setuptools=40.6.3=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.26.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.32.3=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - cuda92=1.0=0
  - pytorch=0.4.1=py36_cuda9.2.148_cudnn7.1.4_1
  - torchvision=0.2.1=py_2
  - pip:
    - atomicwrites==1.2.1
    - attrs==18.2.0
    - hypothesis==3.84.3
    - jupyterlab==0.32.1
    - more-itertools==4.3.0
    - pandas==0.23.1
    - pillow-simd==5.3.0.post0
    - pluggy==0.8.0
    - py==1.7.0
    - pytest==4.0.2
    - torch==0.4.1
    - xlwt==1.3.0
prefix: /home/will/.miniconda3/envs/torchvideo

