name: torchvideo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - av=6.1.0
  - ffmpeg==4.1
  - lintel=1.0
  - numpy=1.15.4
  - cuda90=1.0
  - pytorch=0.4.1
  - python=3.6.6
  - pip=18.1
  - torchvision=0.2.1
  - pre_commit==1.13.0
  - pip:
    - hypothesis==3.84.3
    - pytest==4.0.2
    - pytest-cov==2.6.0
    - pytest-xdist==1.24.0
    - pyfakefs==3.5.5
    - moviepy==0.2.3.5
    - gulpio==531.53
    - sphinx==1.8.3
    - sphinx_autodoc_typehints==1.6.0
    - sphinx_rtd_theme==0.4.2
    - pillow-simd==5.3.0.post0
    - scipy==1.2.0
    - mypy==0.650
