name: torchvideo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - av=6.2.0
  - ffmpeg
  - lintel=1.0
  - numpy=1.17.5
  - pandas==0.25.3
  - pytorch=1.4.0
  - python=3.7.6
  - pip
  - torchvision=0.5.0
  - pre_commit==1.18.1
  - pip:
    - hypothesis==4.32.3
    - pytest==5.3.4
    - pytest-cov==2.8.1
    - pytest-xdist==1.31.0
    - pyfakefs==3.7.1
    - moviepy==1.0.1
    - gulpio==540.66
    - sphinx==2.3.1
    - sphinx_autodoc_typehints==1.10.3
    - sphinx_rtd_theme==0.4.3
    - pillow-simd==7.0.0.post3
    - scipy==1.4.1
    - mypy==0.761
